//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameResult
    {
        public int IdTicketResult { get; set; }
        public int IdGame { get; set; }
        public int IdPlayer { get; set; }
        public decimal MoneyBet { get; set; }
        public int Situation { get; set; }
        public System.DateTime DateResult { get; set; }
    }
}
